// Malt(rmalt) Grammar

Grammar ::= Expr ;

Expr ::= Quote | Eval | HashTable | List | Tuple | Atom ;

Quote ::= '&' Expr ;

Eval ::= '~' Expr ;

HashTable ::= '(' Pair* ')';

Pair ::= Expr ':' Expr ;

List ::=  '(' Expr '.' Expr ')' | '(' Expr* ')' ;

Tuple ::= '[' Expr* ']' ;

Atom ::= None | Bool | char | charstring | rational | int | uint | sym ;

Bool ::= 'false' | 'true' ;

None ::= 'none' ;